In [2]:
import numpy as np

In [2]:
z = np.array([1, 2, 4])

arr = []
for i in range(len(z)):
    elem = np.exp(z[i] - 4) / 7
    arr.append(elem)
arr

[0.007112438338266277, 0.019333611890944673, 0.14285714285714285]

In [7]:
max = np.max(z)
np.exp(z - max) / np.sum(z - max)

array([0.00711244, 0.01933361, 0.14285714])

In [6]:
np.sum(z)

7

In [8]:
2 ** z

array([ 2,  4, 16], dtype=int32)

In [9]:
z-4

array([-3, -2,  0])

In [10]:
np.sum(z-4)

-5

In [32]:
Z = np.array([[1, 2, 3],
             [9, 4, 6],
             [7, 2, 9]])

In [33]:
Z

array([[1, 2, 3],
       [9, 4, 6],
       [7, 2, 9]])

In [34]:
np.max(Z, axis=1, keepdims=True)

array([[3],
       [9],
       [9]])

In [35]:
Z - np.max(Z, axis=1, keepdims=True)

array([[-2, -1,  0],
       [ 0, -5, -3],
       [-2, -7,  0]])

In [36]:
np.exp(Z - np.max(Z, axis=1, keepdims=True))

array([[1.35335283e-01, 3.67879441e-01, 1.00000000e+00],
       [1.00000000e+00, 6.73794700e-03, 4.97870684e-02],
       [1.35335283e-01, 9.11881966e-04, 1.00000000e+00]])

In [42]:
def forward(Z: np.ndarray) -> np.ndarray:
    Z_center = Z - np.max(Z, axis=1, keepdims=True)
        
    num = np.exp(Z_center)
    denom = np.sum(num, axis=1, keepdims=True)

    softmax = num / denom

    return softmax

def backward(Z: np.ndarray, dY: np.ndarray) -> np.ndarray:
    arr = []  
    s = forward(Z)
    ones = np.ones(Z.shape[0]).reshape(Z.shape[0], 1)
    s_minus = ones - s
    diags = s @ s_minus.T
    for row in diags:
        arr.append(np.diagflat(row))
    



    return np.array(arr)


In [54]:
Z = np.array([[1, 2, 3],
             [9, 4, 6],
             [7, 2, 9],
             [1, 5, 5]])

In [55]:
arr = []  
    s = forward(Z)
    ones = np.ones(Z.shape[0]).reshape(Z.shape[0], 1)
    s_minus = ones - s
    diags = s @ s_minus.T
    for row in diags:
        arr.append(np.diagflat(row))

array([[9.00305732e-02, 2.44728471e-01, 6.65240956e-01],
       [9.46499123e-01, 6.37746092e-03, 4.71234165e-02],
       [1.19107257e-01, 8.02538386e-04, 8.80090205e-01],
       [9.07471484e-03, 4.95462643e-01, 4.95462643e-01]])

In [58]:
A = np.ones(4).reshape(4,1) - s

In [59]:
diags = s @ A.T

array([[0.48945694, 0.88187697, 0.40360825, 0.54832714],
       [0.88187697, 0.10187812, 0.84578711, 0.9649031 ],
       [0.40360825, 0.84578711, 0.21125405, 0.56246969],
       [0.54832714, 0.9649031 , 0.56246969, 0.50895119]])

In [1]:
def im2col(X, kernel_shape, stride, pad):
    # n_channels = in_channels
    n_channels = X.shape[3]
    # sliding kernel shape
    kernel_height, kernel_width = kernel_shape
    # padding
    # X_pad is padded input
    # p
    X_pad, p = pad2d(X, pad, kernel_shape, stride)
    X_pad = X_pad.transpose(0, 3, 1, 2)
    X = X.transpose(0, 3, 1, 2)

    i, j, k = im2col_indices(X, kernel_shape, stride, p)
    X_col = X_pad[:, k, i, j]

    X_col = X_col.transpose(1, 2, 0).reshape(
        kernel_height * kernel_width * n_channels, -1
    )

    return X_col, p

In [3]:
Z = np.array([[1, 2, 3],
              [9, 4, 6],
              [7, 2, 9]])

In [ ]:
A = np.array([[1, 2],
              [2, 4]])